### ISSUE TITLE
wiringPi.h / libwiringPi dependency

### ISSUE THREAD

**Issue by afaerber** [Snootlab/lmic_chisterapi#1]
src/OTAA_JoinAndTransmit.c includes **wiringPi.h**, but I do not see such a file in any directory of this project, and no Makefile or script generates it either. So it looks like the main program will not compile currently?

Maybe double-check your local `git status` for untracked files?

**Comment by afaerber** [comment]
Similarly there's `-lwiringPi` in the Makefile, but the README.md does not mention such an external dependency in its `git clone`, `make all` workflow.

**Comment by Snootlab** [comment]
wiringPi is a library for the RaspberryPi, it's an external dependency, the wiringPi.h is in /usr/include.
I will add in the README.md to install the library like this : 
`sudo apt-get update`
`sudo apt-get install wiringpi`

**Comment by afaerber** [comment]
Please also link to the sources (http://wiringpi.com/ ?) for those not using apt-get.
I will try to package it for openSUSE.
